### ISSUE TITLE
The output format is a nightmare

### ISSUE THREAD

**Issue by cosmin-novac** [david-cortes/outliertree#2]
Why is the output a list of lists with nested lists? Why not just a multi-col dataframe, with 1 row per observation? Is there a simple way to transform it that way?

**Comment by david-cortes** [comment]
Because that's not supported in R's `data.frame`. You'd have to use `tibble` or `data.table` to have such a thing.

**Comment by cosmin-novac** [comment]
I'd happily have data.table or tibble instead

Am Fr., 11. Dez. 2020 um 20:11 Uhr schrieb david-cortes <
notifications@github.com>:

**Comment by david-cortes** [comment]
To transform it:
```r
t(data.table::as.data.table(outliers))
```
