### ISSUE TITLE
Extract Rows

### ISSUE THREAD

**Issue by mjholm4242** [david-cortes/outliertree#8]
I am new to R and love outliertree.  I am trying to get a list of suspicious rows and the corresponding column.  I can get it to print out the summary but I cannot figure out how to extract the row number.

In my data, I have dates and times and it would be helpful to print out the date/time and column.  All I get now is Row [1967] - suspicious column ......

Is there any way to get this?

Thank you.
Michael Holm

**Comment by david-cortes** [comment]
You can find an example about extracting this information in the package documentation for the main function:
```r
?outliertree::outlier.tree
```
