### ISSUE TITLE
outlier.tree Hangs Indefinitely with Certain Numeric Columns Present in Dataset

### ISSUE THREAD

**Issue by statadvice** [david-cortes/outliertree#9]
Hello! The outlier.tree process does not complete when running on a dataset with only numeric variables, but it finishes quickly if I remove columns 4 and 6. I haven't identified any specific characteristics in these columns that could be causing the slowdown (or even non-termination).

Keeps executing for hours and even days without terminating:
```
library(outliertree)
library(rio)
selected_data<-import("https://data.statadvice.com/selected_data.xlsx")
outliers_model = outliertree::outlier.tree(selected_data)

```

Works fast:
```
library(outliertree)
library(rio)
selected_data<-import("https://data.statadvice.com/selected_data.xlsx")[,-c(4,6)]
outliers_model = outliertree::outlier.tree(selected_data)

```

**Comment by david-cortes** [comment]
Thanks for the bug report. I unfortunately cannot access the domain `data.statadvice.com` and thus cannot download the file.

Would you be able to attach it here, or to upload it to some other service like dropbox?

Also a few questions:
* What kind of setup is this? (e.g. operating system, CPU architecture, etc.)
    * Are you using some platform where the type `long double` would correspond to 128-bit floating points? (e.g. PPC, some ARM platforms I think)
* Did you install this package from source, or did you download a pre-built version from CRAN?
* What kind of size does the data have, and what kind of values do the problematic columns have? e.g. are they all ones and zeros, non-negative numbers, very small numbers, etc.

**Comment by statadvice** [comment]
@david-cortes Here is the data file:
[selected_data.xlsx](https://github.com/user-attachments/files/16881795/selected_data.xlsx)
OS: Windows 10, 64bit
CPU: x64 (64-bit)
pre-built version from cran
the data is 3200 obs of 6 numeric variables found in the 174KB Excel file found above

**Comment by david-cortes** [comment]
Thanks. I was able to download the data and can reproduce the issue - will investigate.

**Comment by david-cortes** [comment]
Thanks, should be solved now. It will take a while for the update to reach CRAN, but in the meantime, the updated version can be installed from github:
```r
remotes::install_github("david-cortes/outliertree")
```
